version: "3.8"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: .
      dockerfile: ./docker-compose/app/Dockerfile
    volumes:
      - .:/var/www/
    depends_on:
      - db
    networks:
      - invoice

  db:
    image: mysql:8.0
    container_name: invoice-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - invoice

  nginx:
    image: nginx:alpine
    container_name: invoice-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - invoice

networks:
  invoice:
    driver: bridge
